
name: Update dashboard data (weekly)

on:
  schedule:
    - cron: "0 1 * * 1"   # 每週一 09:00 台北時間 (UTC+8)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch & build data.json
        run: python scripts/fetch_and_build.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data.json
          git commit -m "chore: weekly data refresh" || echo "No changes to commit"
          git push
